// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH6V1XK8fS19oJZmzcDWuumEXLpWSOPkY',
    appId: '1:1084769880827:web:e05c807de7f0fcf3fc7e5e',
    messagingSenderId: '1084769880827',
    projectId: 'champions-ring-app',
    authDomain: 'champions-ring-app.firebaseapp.com',
    storageBucket: 'champions-ring-app.firebasestorage.app',
    measurementId: 'G-6RZZKBEP6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEPPgPp-vKi47VFn32pD6A3CxLQxN38Q4',
    appId: '1:1084769880827:android:1ae050c932e436bffc7e5e',
    messagingSenderId: '1084769880827',
    projectId: 'champions-ring-app',
    storageBucket: 'champions-ring-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kwenMdB9g4lrDGH-4JdUDP610Ub0ds4',
    appId: '1:1084769880827:ios:21298b36b16074f9fc7e5e',
    messagingSenderId: '1084769880827',
    projectId: 'champions-ring-app',
    storageBucket: 'champions-ring-app.firebasestorage.app',
    iosBundleId: 'com.example.championsRingApp',
  );
}
